services:
  kafka:
    image: claude_auto/kafka:3.9.0
    container_name: kafka-test
    hostname: kafka
    ports:
      - "9092:9092"
    command: >
      bash -c "export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092 &&
               export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT &&
               export KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093 &&
               export KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093 &&
               export KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER &&
               export KAFKA_AUTO_CREATE_TOPICS_ENABLE=true &&
               export KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 &&
               export KAFKA_NODE_ID=1 &&
               export KAFKA_PROCESS_ROLES=broker,controller &&
               export KAFKA_CLUSTER_ID=5L6g3nShT-eMCtK--X86sw &&
               /opt/kafka/bin/kafka-storage.sh format --config /opt/kafka/config/kraft/server.properties --cluster-id 5L6g3nShT-eMCtK--X86sw &&
               /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties"
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data:
